# Generated by Django 5.2.4 on 2026-05-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
