# Generated by Django 5.2.4 on 2026-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0002_patientinformation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
