# Generated by Django 5.2.4 on 2026-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0003_patientinformation_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='address',
        ),
    ]
