# Generated by Django 5.2.4 on 2026-05-23 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0004_remove_patientinformation_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
