# Generated by Django 5.2.4 on 2026-05-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0005_patientinformation_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=255)),
                ('member_number', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_registration.patientinformation')),
            ],
        ),
    ]
